Avoid crashing under certain circumnstances involving search
Following was hit when navigating while search is active. So the worker
thread does the searching and the UI one tries to figure out what's under
the cursor, avoid that by locking things while searching.

error: cycle in tree (parents)
warning: cannot load object (0 0 R) into cache

Thread 1 "llpp" received signal SIGSEGV, Segmentation fault.
0x000055555563589e in fz_do_catch (ctx=0x0) at source/fitz/error.c:194
194		return (ctx->error->top--)->code > 1;
(gdb) thr app all bt

Thread 3 (Thread 0x7ffff48e6700 (LWP 11289)):
#0  0x00007ffff7aa7a54 in __longjmp () from /usr/lib/libc.so.6
#1  0x00007ffff7aa79e0 in siglongjmp () from /usr/lib/libc.so.6
#2  0x00007ffff7fa0d0e in siglongjmp@GLIBC_2.2.5 () from /usr/lib/libpthread.so.0
#3  0x0000555555635703 in throw (ctx=0x555557e65150) at source/fitz/error.c:118
#4  0x0000555555635b3b in fz_rethrow (ctx=0x555557e65150) at source/fitz/error.c:246
#5  0x00005555556a20a2 in pdf_lookup_page_loc_imp (ctx=0x555557e65150, doc=0x7fffe8001e40, node=0x7fffe8013870, skip=0x7ffff48e58cc, parentp=0x0, indexp=0x0) at source/pdf/pdf-page.c:176
#6  0x00005555556a2183 in pdf_lookup_page_loc (ctx=0x555557e65150, doc=0x7fffe8001e40, needle=1521, parentp=0x0, indexp=0x0) at source/pdf/pdf-page.c:193
#7  0x00005555556a21fb in pdf_lookup_page_obj (ctx=0x555557e65150, doc=0x7fffe8001e40, needle=1521) at source/pdf/pdf-page.c:202
#8  0x000055555573f680 in pdf_parse_link_dest (ctx=0x555557e65150, doc=0x7fffe8001e40, dest=0x7fffe91039a0) at source/pdf/pdf-link.c:73
#9  0x00005555557401f8 in pdf_load_link (ctx=0x555557e65150, doc=0x7fffe8001e40, dict=0x7fffe80c2650, pagenum=195, page_ctm=...) at source/pdf/pdf-link.c:274
#10 0x00005555557403e5 in pdf_load_link_annots (ctx=0x555557e65150, doc=0x7fffe8001e40, annots=0x7fffe80c2080, pagenum=195, page_ctm=...) at source/pdf/pdf-link.c:314
#11 0x00005555556a4dc6 in pdf_load_page (ctx=0x555557e65150, doc=0x7fffe8001e40, number=195) at source/pdf/pdf-page.c:1096
#12 0x00005555556101f1 in fz_load_page (ctx=0x555557e65150, doc=0x7fffe8001e40, number=195) at source/fitz/document.c:465
#13 0x00005555555f5f68 in search (forward=<optimized out>, y=0, pageno=195, re=0x7ffff48e5dc0) at ./link.c:1224
#14 mainloop (unused=<optimized out>) at ./link.c:1533
#15 0x00007ffff7f97a9d in start_thread () from /usr/lib/libpthread.so.0
#16 0x00007ffff7b6bb23 in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7ffff52cd700 (LWP 11288)):
#0  0x00007ffff7f9dafc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007ffff5c7cc94 in ?? () from /usr/lib/dri/i965_dri.so
#2  0x00007ffff5c7c9b8 in ?? () from /usr/lib/dri/i965_dri.so
#3  0x00007ffff7f97a9d in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007ffff7b6bb23 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7533740 (LWP 11284)):
#0  0x000055555563589e in fz_do_catch (ctx=0x0) at source/fitz/error.c:194
#1  0x00005555556bd71d in pdf_resolve_indirect (ctx=0x1, ref=0x0) at source/pdf/pdf-xref.c:2077
#2  0x0000555557ef4720 in ?? ()
#3  0x00007fffffffe1d0 in ?? ()
#4  0x00007ffff7fa0d0e in siglongjmp@GLIBC_2.2.5 () from /usr/lib/libpthread.so.0
#5  0x0000555555635703 in throw (ctx=0x555555635703 <throw+97>) at source/fitz/error.c:118
#6  0x0000555557e65150 in ?? ()
#7  0x00007fffffffe1f0 in ?? ()
#8  0x0000555555635b3b in fz_rethrow (ctx=0x555557e65150) at source/fitz/error.c:246
#9  0x00005555556a0c5f in pdf_dict_get_inheritable (ctx=0x555557e65150, node=0x7fffe801e990, key=0x60) at source/pdf/pdf-object.c:2235
#10 0x00005555556a3694 in pdf_page_obj_transform (ctx=0x555557e65150, pageobj=0x7fffe801ea50, page_mediabox=0x7fffffffe2d0, page_ctm=0x7fffffffe3b0) at source/pdf/pdf-page.c:656
#11 0x00005555556a3b16 in pdf_page_transform (ctx=0x555557e65150, page=0x7fffe8a8d2a0, page_mediabox=0x0, page_ctm=0x7fffffffe3b0) at source/pdf/pdf-page.c:696
#12 0x000055555567d5d8 in pdf_bound_annot (ctx=0x555557e65150, annot=0x7fffe8e18f50) at source/pdf/pdf-annot.c:150
#13 0x00005555555f9ce3 in getannot (y=<optimized out>, x=933, page=0x7fffe8d32fb0) at ./link.c:2390
#14 ml_whatsunder (ptr_v=<optimized out>, x_v=<optimized out>, y_v=<optimized out>) at ./link.c:2732
#15 0x0000555555991891 in caml_interprete ()
#16 0x00005555559938a4 in caml_main ()
#17 0x00005555555eaa6c in main () at ./link.c:1167